# Generated by Django 3.0.7 on 2020-06-14 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('idade', models.IntegerField(blank=True, default=10, null=True, verbose_name='Idade')),
                ('login', models.CharField(blank=True, max_length=255, null=True, verbose_name='Login')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=10, null=True, verbose_name='Genero')),
                ('nivel_de_autismo', models.CharField(blank=True, choices=[('1', 'Criança Nível 1 - Exigindo Apoio'), ('2', 'Criança Nível 2 - Exigindo Apoio Substancial'), ('3', 'Criança Nível 3 - Exigindo Apoio Muito Substancial'), ('4', 'Criança Nível Desconhecido'), ('5', 'Criança Sem Autimo')], max_length=50, null=True, verbose_name='Nível de Autismo')),
                ('definicao_a_1', models.CharField(blank=True, choices=[('Definition_A_1_hig', 'A1 Alta Intensidade'), ('Definition_A_1_low', 'A1 Baixa Intensidade'), ('Definition_A_1_med', 'A1 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao A-1')),
                ('definicao_a_2', models.CharField(blank=True, choices=[('Definition_A_2_hig', 'A2 Alta Intensidade'), ('Definition_A_2_low', 'A2 Baixa Intensidade'), ('Definition_A_2_med', 'A2 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao A-2')),
                ('definicao_a_3', models.CharField(blank=True, choices=[('Definition_A_3_hig', 'A3 Alta Intensidade'), ('Definition_A_3_low', 'A3 Baixa Intensidade'), ('Definition_A_3_med', 'A3 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao A-3')),
                ('definicao_b_1', models.CharField(blank=True, choices=[('Definition_B_1_hig', 'B1 Alta Intensidade'), ('Definition_B_1_low', 'B1 Baixa Intensidade'), ('Definition_B_1_med', 'B1 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao B-1')),
                ('definicao_b_2', models.CharField(blank=True, choices=[('Definition_B_2_hig', 'B2 Alta Intensidade'), ('Definition_B_2_low', 'B2 Baixa Intensidade'), ('Definition_B_2_med', 'B2 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao B-2')),
                ('definicao_b_3', models.CharField(blank=True, choices=[('Definition_B_3_hig', 'B3 Alta Intensidade'), ('Definition_B_3_low', 'B3 Baixa Intensidade'), ('Definition_B_3_med', 'B3 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao B-3')),
                ('definicao_b_4', models.CharField(blank=True, choices=[('Definition_B_4_hig', 'B4 Alta Intensidade'), ('Definition_B_4_low', 'B4 Baixa Intensidade'), ('Definition_B_4_med', 'B4 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao B-4')),
                ('definicao_c', models.CharField(blank=True, choices=[('', ''), ('Definition_C', 'C')], max_length=20, null=True, verbose_name='Definiçao C')),
                ('definicao_d', models.CharField(blank=True, choices=[('', ''), ('Definition_D', 'D')], max_length=20, null=True, verbose_name='Definiçao D')),
                ('definicao_e', models.CharField(blank=True, choices=[('', ''), ('Definition_E', 'E')], max_length=20, null=True, verbose_name='Definiçao E')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto_er',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo do objeto de aprendizagem')),
                ('sub_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub titulo')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('area_de_conhecimento', models.CharField(blank=True, choices=[('Art', 'Artes'), ('Foreign_Languages', 'Línguas Extrangeiras'), ('Geography', 'Geografia'), ('History', 'História'), ('Math', 'Matemática'), ('Natural_Sciences', 'Ciências Naturais'), ('Physical_Education', 'Educação Física'), ('Portuguese_Language', 'Língua Portuguesa'), ('Miscellaneous ', 'Conhecimentos Gerais')], max_length=50, null=True, verbose_name='Área de Conhecimento')),
                ('dificuldade', models.CharField(blank=True, choices=[('1', 'Muito Fácil'), ('2', 'Fácil'), ('3', 'Mediano'), ('4', 'Difícil'), ('5', 'Muito Difícil')], max_length=20, null=True, verbose_name='Nível de dificuldade')),
                ('tipo_de_arquivo', models.CharField(blank=True, choices=[('1', 'Text'), ('2', 'Image'), ('3', 'Audio'), ('4', 'Video')], max_length=10, null=True, verbose_name='Tipo de arquivo')),
                ('texto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto')),
                ('idioma', models.CharField(blank=True, choices=[('1', 'Portugues'), ('2', 'Espanhol'), ('3', 'Ingles')], max_length=10, null=True, verbose_name='Idioma')),
                ('arquivo_1', models.FileField(blank=True, null=True, upload_to='arquivos/objeto_er/', verbose_name='Arquivo Principal')),
                ('arquivo_2', models.FileField(blank=True, null=True, upload_to='arquivos/objeto_er/', verbose_name='Arquivo Secundário:')),
                ('duracao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Duração em Minutos')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('prefab', models.CharField(max_length=50)),
                ('tamanho', models.CharField(default='1.0', max_length=10, verbose_name='Tamanho(Usar virgula): ')),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Objeto_er_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('objeto_er', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_app.Objeto_er')),
            ],
        ),
        migrations.AddField(
            model_name='objeto_er',
            name='personagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website_app.Personagem'),
        ),
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('objeto_er', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_app.Objeto_er')),
            ],
        ),
    ]
