# Generated by Django 3.0.7 on 2020-09-03 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import storages.backends.ftp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto_er',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo do objeto de aprendizagem')),
                ('sub_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub titulo')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('area_de_conhecimento', models.CharField(blank=True, choices=[('Art', 'Artes'), ('Foreign_Languages', 'Línguas Extrangeiras'), ('Geography', 'Geografia'), ('History', 'História'), ('Math', 'Matemática'), ('Natural_Sciences', 'Ciências Naturais'), ('Physical_Education', 'Educação Física'), ('Portuguese_Language', 'Língua Portuguesa'), ('Miscellaneous ', 'Conhecimentos Gerais')], max_length=50, null=True, verbose_name='Área de Conhecimento')),
                ('dificuldade', models.CharField(blank=True, choices=[('1', 'Muito Fácil'), ('2', 'Fácil'), ('3', 'Mediano'), ('4', 'Difícil'), ('5', 'Muito Difícil')], max_length=20, null=True, verbose_name='Nível de dificuldade')),
                ('tipo_de_arquivo', models.CharField(blank=True, choices=[('1', 'Text'), ('2', 'Image'), ('3', 'Audio'), ('4', 'Video')], max_length=10, null=True, verbose_name='Tipo de arquivo')),
                ('texto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto')),
                ('idioma', models.CharField(blank=True, choices=[('1', 'Portugues'), ('2', 'Espanhol'), ('3', 'Ingles')], max_length=10, null=True, verbose_name='Idioma')),
                ('arquivo_1', models.FileField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to='arquivos/objeto_er/', verbose_name='Arquivo Principal')),
                ('arquivo_2', models.FileField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to='arquivos/objeto_er/', verbose_name='Arquivo Secundário:')),
                ('duracao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Duração em Minutos')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('prefab', models.CharField(max_length=50)),
                ('tamanho', models.CharField(default='1.0', max_length=10, verbose_name='Tamanho: ')),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Objeto_er_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('objeto_er', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_app.Objeto_er')),
            ],
        ),
        migrations.AddField(
            model_name='objeto_er',
            name='personagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website_app.Personagem'),
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('online', models.BooleanField(default=False)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('animacao', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_de_autismo', models.CharField(blank=True, choices=[('1', 'Criança Nível 1 - Exigindo Apoio'), ('2', 'Criança Nível 2 - Exigindo Apoio Substancial'), ('3', 'Criança Nível 3 - Exigindo Apoio Muito Substancial'), ('4', 'Criança Nível Desconhecido'), ('5', 'Criança Sem Autismo')], max_length=50, null=True, verbose_name='Nível de Autismo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('objeto_er', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_app.Objeto_er')),
            ],
        ),
    ]
