# Generated by Django 3.0.7 on 2020-08-19 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_a_1',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_a_2',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_a_3',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_b_1',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_b_2',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_b_3',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_b_4',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_c',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_d',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_e',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='login',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='password',
        ),
        migrations.AddField(
            model_name='jogador',
            name='animacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jogador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
