# Generated by Django 2.2.4 on 2019-08-16 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparecimento',
            name='objeto_er',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_app.Objeto_ER'),
        ),
        migrations.AlterField(
            model_name='captura',
            name='objeto_er',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_app.Objeto_ER'),
        ),
        migrations.AlterField(
            model_name='objeto_er',
            name='area_de_conhecimento',
            field=models.CharField(blank=True, choices=[('Art', 'Artes'), ('Foreign_Languages', 'Línguas Extrangeiras'), ('Geography', 'Geografia'), ('History', 'História'), ('Math', 'Matemática'), ('Natural_Sciences', 'Ciências Naturais'), ('Physical_Education', 'Educação Física'), ('Portuguese_Language', 'Língua Portuguesa'), ('Miscellaneous ', 'Conhecimentos Gerais')], max_length=50, null=True, verbose_name='Área de Conhecimento'),
        ),
        migrations.AlterField(
            model_name='objeto_er',
            name='arquivo_1',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/objeto_er/', verbose_name='Arquivo Principal'),
        ),
        migrations.AlterField(
            model_name='objeto_er',
            name='arquivo_2',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/objeto_er/', verbose_name='Arquivo Secundário:'),
        ),
        migrations.AlterField(
            model_name='objeto_er',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objeto_er',
            name='dificuldade',
            field=models.CharField(blank=True, choices=[('1', 'Muito Fácil'), ('2', 'Fácil'), ('3', 'Mediano'), ('4', 'Difícil'), ('5', 'Muito Difícil')], max_length=20, null=True, verbose_name='Nível de dificuldade'),
        ),
        migrations.AlterField(
            model_name='objeto_er',
            name='duracao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Duração em Minutos'),
        ),
        migrations.AlterField(
            model_name='objeto_er',
            name='idioma',
            field=models.CharField(blank=True, choices=[('1', 'Portugues'), ('2', 'Espanhol'), ('3', 'Ingles')], max_length=10, null=True, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='objeto_er',
            name='tipo_de_arquivo',
            field=models.CharField(blank=True, choices=[('1', 'Text'), ('2', 'Image'), ('3', 'Audio'), ('4', 'Video')], max_length=10, null=True, verbose_name='Tipo de arquivo'),
        ),
        migrations.AlterField(
            model_name='objeto_er',
            name='tipo_de_objeto',
            field=models.CharField(blank=True, choices=[('1', 'Monstro'), ('2', 'Mensagem')], max_length=10, null=True, verbose_name='Tipo de objeto de aprendizagem'),
        ),
    ]
