# Generated by Django 3.0.7 on 2020-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='tamanho',
            field=models.CharField(default='1.0', max_length=10, verbose_name='Tamanho: '),
        ),
    ]
