# Generated by Django 3.0.7 on 2020-06-26 13:44

from django.db import migrations, models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto_er',
            name='arquivo_1',
            field=models.FileField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to='arquivos/objeto_er/', verbose_name='Arquivo Principal'),
        ),
        migrations.AlterField(
            model_name='objeto_er',
            name='arquivo_2',
            field=models.FileField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to='arquivos/objeto_er/', verbose_name='Arquivo Secundário:'),
        ),
    ]
