# Generated by Django 2.2.4 on 2019-08-16 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_auto_20190815_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='captura',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='captura',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='captura',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
