# Generated by Django 2.2.4 on 2019-08-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_auto_20190816_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_a_1',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_a_2',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_a_3',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_b_1',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_b_2',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_b_3',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_b_4',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_c',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_d',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='definicao_e',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='nivel_de_autismo',
        ),
    ]
