# Generated by Django 2.2.4 on 2019-08-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_auto_20190816_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='login',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='password',
        ),
    ]
