# Generated by Django 2.2.4 on 2019-08-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_auto_20190816_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='nome',
        ),
    ]
