# Generated by Django 2.2.4 on 2019-08-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0006_remove_jogador_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='definicao_a_1',
            field=models.CharField(blank=True, choices=[('Definition_A_1_hig', 'A1 Alta Intensidade'), ('Definition_A_1_low', 'A1 Baixa Intensidade'), ('Definition_A_1_med', 'A1 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao A-1'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='definicao_a_2',
            field=models.CharField(blank=True, choices=[('Definition_A_2_hig', 'A2 Alta Intensidade'), ('Definition_A_2_low', 'A2 Baixa Intensidade'), ('Definition_A_2_med', 'A2 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao A-2'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='definicao_a_3',
            field=models.CharField(blank=True, choices=[('Definition_A_3_hig', 'A3 Alta Intensidade'), ('Definition_A_3_low', 'A3 Baixa Intensidade'), ('Definition_A_3_med', 'A3 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao A-3'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='definicao_b_1',
            field=models.CharField(blank=True, choices=[('Definition_B_1_hig', 'B1 Alta Intensidade'), ('Definition_B_1_low', 'B1 Baixa Intensidade'), ('Definition_B_1_med', 'B1 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao B-1'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='definicao_b_2',
            field=models.CharField(blank=True, choices=[('Definition_B_2_hig', 'B2 Alta Intensidade'), ('Definition_B_2_low', 'B2 Baixa Intensidade'), ('Definition_B_2_med', 'B2 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao B-2'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='definicao_b_3',
            field=models.CharField(blank=True, choices=[('Definition_B_3_hig', 'B3 Alta Intensidade'), ('Definition_B_3_low', 'B3 Baixa Intensidade'), ('Definition_B_3_med', 'B3 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao B-3'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='definicao_b_4',
            field=models.CharField(blank=True, choices=[('Definition_B_4_hig', 'B4 Alta Intensidade'), ('Definition_B_4_low', 'B4 Baixa Intensidade'), ('Definition_B_4_med', 'B4 Média Intensidade')], max_length=20, null=True, verbose_name='Definiçao B-4'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='definicao_c',
            field=models.CharField(blank=True, choices=[('', ''), ('Definition_C', 'C')], max_length=20, null=True, verbose_name='Definiçao C'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='definicao_d',
            field=models.CharField(blank=True, choices=[('', ''), ('Definition_D', 'D')], max_length=20, null=True, verbose_name='Definiçao D'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='definicao_e',
            field=models.CharField(blank=True, choices=[('', ''), ('Definition_E', 'E')], max_length=20, null=True, verbose_name='Definiçao E'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='idade',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='nivel_de_autismo',
            field=models.CharField(blank=True, choices=[('1', 'Criança Nível 1 - Exigindo Apoio'), ('2', 'Criança Nível 2 - Exigindo Apoio Substancial'), ('3', 'Criança Nível 3 - Exigindo Apoio Muito Substancial'), ('4', 'Criança Nível Desconhecido'), ('5', 'Criança Sem Autimo')], max_length=50, null=True, verbose_name='Nível de Autismo'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
