# Generated by Django 2.2.4 on 2019-08-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_auto_20190816_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aparecimento',
            new_name='Objeto_er_map',
        ),
    ]
