# Generated by Django 2.2.4 on 2019-09-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0008_auto_20190816_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('prefab', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='objeto_er',
            name='tipo_de_objeto',
        ),
        migrations.AlterField(
            model_name='jogador',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=10, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='idade',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='objeto_er_map',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='objeto_er_map',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='objeto_er',
            name='personagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website_app.Personagem'),
        ),
    ]
