# Generated by Django 2.2.4 on 2019-09-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0009_auto_20190908_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='tamanho',
            field=models.CharField(default='1,0', max_length=10, verbose_name='Tamanho(Usar virgula): '),
        ),
    ]
